version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - 9090:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        networks:
            - app_network

    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=postgresql
            - DB_PORT=5432
            - DB_DATABASE=carloans
            - DB_USERNAME=carloans
            - DB_PASSWORD=carloans_password
        depends_on:
            - postgresql
        networks:
            - app_network

    postgresql:
        image: postgres:latest
        environment:
            - POSTGRES_DB=carloans
            - POSTGRES_USER=carloans
            - POSTGRES_PASSWORD=carloans_password
        ports:
            - 5432:5432
        networks:
            - app_network

networks:
    app_network:
